<?php
session_start();

try {
    $conn = new PDO("mysql:host=$servername", $username, $password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $conn->exec($sql);
    }
catch(PDOException $e)
    {
    // echo $sql . "<br>" . $e->getMessage(); <-----Dunno why
    }

    console.log("logged in");
?>
<html lang="en">
<head>
    <link href="login.css" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div class="background"></div>
        <div class="block-style">
        <div class="header">
            <p>Login</p>
        </div>
        <form action="./login.php" method="post">
            <div class="input-group">
                <label>Username</label>
                <input type="text" name="username" required>
            </div>
            
            <div class="input-group">
                <label>Password</label>
                <input type="password" name="password" required>
            </div>
            <div class="input-group">
                <button class="btn" type="submit" name="submit">Submit</button>
            </div>
        </form>
        </div>
</body>
</html>